version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:ashishlal@db:5432/itemsdb

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ashishlal
      POSTGRES_DB: itemsdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      
volumes:
  pgdata:
