services:
  - type: web
    name: fullstack-app
    env: docker
    plan: free
    repo: https://github.com/ashishmathco/podman-test
    dockerCommand: docker-compose up --build
    envVars:
      - key: PORT
        value: 3000
