services:
  - type: web
    name: backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port 8000"
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: itemsdb
          property: connectionString
    plan: free
    regions:
      - oregon

  - type: web
    name: frontend
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    regions:
      - oregon

databases:
  - name: itemsdb
    engine: postgres
    version: "14"
    plan: free
    envVars:
      - key: POSTGRES_USER
        value: "postgres"
      - key: POSTGRES_PASSWORD
        value: "ashishlal"
      - key: POSTGRES_DB
        value: "itemsdb"
    regions:
      - oregon
